### ISSUE TITLE
parse error when blend with hsl()

### ISSUE THREAD

**Issue by FourwingsY** [ianstormtaylor/css-color-function#24]
```css
.test {
  color: color(hsl(210, 10%, 85%) blend(hsl(330, 50%, 70%) 50%));
}
```

Error message says: Unable to parse color from string "hsl(330,"
can get the bug here too: http://cssnext.io/playground/
